/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.parser;

import dplusplus.node.*;
import dplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTFamily(@SuppressWarnings("unused") TFamily node)
    {
        this.index = 0;
    }

    @Override
    public void caseTSim(@SuppressWarnings("unused") TSim node)
    {
        this.index = 1;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 2;
    }

    @Override
    public void caseTAnswer(@SuppressWarnings("unused") TAnswer node)
    {
        this.index = 3;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 4;
    }

    @Override
    public void caseTStart(@SuppressWarnings("unused") TStart node)
    {
        this.index = 5;
    }

    @Override
    public void caseTFinish(@SuppressWarnings("unused") TFinish node)
    {
        this.index = 6;
    }

    @Override
    public void caseTProcedure(@SuppressWarnings("unused") TProcedure node)
    {
        this.index = 7;
    }

    @Override
    public void caseTAbreColchete(@SuppressWarnings("unused") TAbreColchete node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFechaColchete(@SuppressWarnings("unused") TFechaColchete node)
    {
        this.index = 9;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 12;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 13;
    }

    @Override
    public void caseTObject(@SuppressWarnings("unused") TObject node)
    {
        this.index = 14;
    }

    @Override
    public void caseTUnalterable(@SuppressWarnings("unused") TUnalterable node)
    {
        this.index = 15;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 16;
    }

    @Override
    public void caseTInCaseThat(@SuppressWarnings("unused") TInCaseThat node)
    {
        this.index = 17;
    }

    @Override
    public void caseTAslongas(@SuppressWarnings("unused") TAslongas node)
    {
        this.index = 18;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 19;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 20;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 21;
    }

    @Override
    public void caseTMaiorQue(@SuppressWarnings("unused") TMaiorQue node)
    {
        this.index = 22;
    }

    @Override
    public void caseTMenorQue(@SuppressWarnings("unused") TMenorQue node)
    {
        this.index = 23;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 24;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 25;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 26;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 27;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 28;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 29;
    }

    @Override
    public void caseTSepararExpressao(@SuppressWarnings("unused") TSepararExpressao node)
    {
        this.index = 30;
    }

    @Override
    public void caseTEComercial(@SuppressWarnings("unused") TEComercial node)
    {
        this.index = 31;
    }

    @Override
    public void caseTInteiro(@SuppressWarnings("unused") TInteiro node)
    {
        this.index = 32;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 33;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 34;
    }

    @Override
    public void caseTIdClasse(@SuppressWarnings("unused") TIdClasse node)
    {
        this.index = 35;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 36;
    }
}
