/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import dplusplus.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAEmptyIgnore(AEmptyIgnore node);

    void caseTFamily(TFamily node);
    void caseTSim(TSim node);
    void caseTNao(TNao node);
    void caseTAnswer(TAnswer node);
    void caseTNumber(TNumber node);
    void caseTStart(TStart node);
    void caseTFinish(TFinish node);
    void caseTProcedure(TProcedure node);
    void caseTAbreColchete(TAbreColchete node);
    void caseTFechaColchete(TFechaColchete node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTObject(TObject node);
    void caseTUnalterable(TUnalterable node);
    void caseTFunction(TFunction node);
    void caseTInCaseThat(TInCaseThat node);
    void caseTAslongas(TAslongas node);
    void caseTAnd(TAnd node);
    void caseTNot(TNot node);
    void caseTOr(TOr node);
    void caseTMaiorQue(TMaiorQue node);
    void caseTMenorQue(TMenorQue node);
    void caseTIgual(TIgual node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTPonto(TPonto node);
    void caseTVirgula(TVirgula node);
    void caseTSepararExpressao(TSepararExpressao node);
    void caseTEComercial(TEComercial node);
    void caseTInteiro(TInteiro node);
    void caseTReal(TReal node);
    void caseTIdentificador(TIdentificador node);
    void caseTIdClasse(TIdClasse node);
    void caseTEspacoEmBranco(TEspacoEmBranco node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
