/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAcessoAtributoFator extends PFator
{
    private PAcessoAtributo _acessoAtributo_;

    public AAcessoAtributoFator()
    {
        // Constructor
    }

    public AAcessoAtributoFator(
        @SuppressWarnings("hiding") PAcessoAtributo _acessoAtributo_)
    {
        // Constructor
        setAcessoAtributo(_acessoAtributo_);

    }

    @Override
    public Object clone()
    {
        return new AAcessoAtributoFator(
            cloneNode(this._acessoAtributo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAcessoAtributoFator(this);
    }

    public PAcessoAtributo getAcessoAtributo()
    {
        return this._acessoAtributo_;
    }

    public void setAcessoAtributo(PAcessoAtributo node)
    {
        if(this._acessoAtributo_ != null)
        {
            this._acessoAtributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._acessoAtributo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._acessoAtributo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._acessoAtributo_ == child)
        {
            this._acessoAtributo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._acessoAtributo_ == oldChild)
        {
            setAcessoAtributo((PAcessoAtributo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
