/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAcessoAtributo extends PAcessoAtributo
{
    private final LinkedList<PAcessoId> _acessoId_ = new LinkedList<PAcessoId>();
    private PAtributo _atributo_;

    public AAcessoAtributo()
    {
        // Constructor
    }

    public AAcessoAtributo(
        @SuppressWarnings("hiding") List<?> _acessoId_,
        @SuppressWarnings("hiding") PAtributo _atributo_)
    {
        // Constructor
        setAcessoId(_acessoId_);

        setAtributo(_atributo_);

    }

    @Override
    public Object clone()
    {
        return new AAcessoAtributo(
            cloneList(this._acessoId_),
            cloneNode(this._atributo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAcessoAtributo(this);
    }

    public LinkedList<PAcessoId> getAcessoId()
    {
        return this._acessoId_;
    }

    public void setAcessoId(List<?> list)
    {
        for(PAcessoId e : this._acessoId_)
        {
            e.parent(null);
        }
        this._acessoId_.clear();

        for(Object obj_e : list)
        {
            PAcessoId e = (PAcessoId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._acessoId_.add(e);
        }
    }

    public PAtributo getAtributo()
    {
        return this._atributo_;
    }

    public void setAtributo(PAtributo node)
    {
        if(this._atributo_ != null)
        {
            this._atributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._acessoId_)
            + toString(this._atributo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._acessoId_.remove(child))
        {
            return;
        }

        if(this._atributo_ == child)
        {
            this._atributo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAcessoId> i = this._acessoId_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAcessoId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._atributo_ == oldChild)
        {
            setAtributo((PAtributo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
