/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAcessoAcessoAtributo extends PAcessoAtributo
{
    private final LinkedList<TIdComposto> _idComposto_ = new LinkedList<TIdComposto>();
    private PAtributo _atributo_;

    public AAcessoAcessoAtributo()
    {
        // Constructor
    }

    public AAcessoAcessoAtributo(
        @SuppressWarnings("hiding") List<?> _idComposto_,
        @SuppressWarnings("hiding") PAtributo _atributo_)
    {
        // Constructor
        setIdComposto(_idComposto_);

        setAtributo(_atributo_);

    }

    @Override
    public Object clone()
    {
        return new AAcessoAcessoAtributo(
            cloneList(this._idComposto_),
            cloneNode(this._atributo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAcessoAcessoAtributo(this);
    }

    public LinkedList<TIdComposto> getIdComposto()
    {
        return this._idComposto_;
    }

    public void setIdComposto(List<?> list)
    {
        for(TIdComposto e : this._idComposto_)
        {
            e.parent(null);
        }
        this._idComposto_.clear();

        for(Object obj_e : list)
        {
            TIdComposto e = (TIdComposto) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._idComposto_.add(e);
        }
    }

    public PAtributo getAtributo()
    {
        return this._atributo_;
    }

    public void setAtributo(PAtributo node)
    {
        if(this._atributo_ != null)
        {
            this._atributo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idComposto_)
            + toString(this._atributo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idComposto_.remove(child))
        {
            return;
        }

        if(this._atributo_ == child)
        {
            this._atributo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TIdComposto> i = this._idComposto_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdComposto) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._atributo_ == oldChild)
        {
            setAtributo((PAtributo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
