/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAndExpAnd extends PExpAnd
{
    private PExpAnd _expAnd_;
    private TAnd _and_;
    private PExpIgual _expIgual_;

    public AAndExpAnd()
    {
        // Constructor
    }

    public AAndExpAnd(
        @SuppressWarnings("hiding") PExpAnd _expAnd_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExpIgual _expIgual_)
    {
        // Constructor
        setExpAnd(_expAnd_);

        setAnd(_and_);

        setExpIgual(_expIgual_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpAnd(
            cloneNode(this._expAnd_),
            cloneNode(this._and_),
            cloneNode(this._expIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpAnd(this);
    }

    public PExpAnd getExpAnd()
    {
        return this._expAnd_;
    }

    public void setExpAnd(PExpAnd node)
    {
        if(this._expAnd_ != null)
        {
            this._expAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAnd_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAnd_)
            + toString(this._and_)
            + toString(this._expIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAnd_ == child)
        {
            this._expAnd_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAnd_ == oldChild)
        {
            setExpAnd((PExpAnd) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
