/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAtributos extends PAtributos
{
    private final LinkedList<PDecGeral> _decGeral_ = new LinkedList<PDecGeral>();

    public AAtributos()
    {
        // Constructor
    }

    public AAtributos(
        @SuppressWarnings("hiding") List<?> _decGeral_)
    {
        // Constructor
        setDecGeral(_decGeral_);

    }

    @Override
    public Object clone()
    {
        return new AAtributos(
            cloneList(this._decGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributos(this);
    }

    public LinkedList<PDecGeral> getDecGeral()
    {
        return this._decGeral_;
    }

    public void setDecGeral(List<?> list)
    {
        for(PDecGeral e : this._decGeral_)
        {
            e.parent(null);
        }
        this._decGeral_.clear();

        for(Object obj_e : list)
        {
            PDecGeral e = (PDecGeral) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decGeral_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decGeral_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecGeral> i = this._decGeral_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecGeral) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
