/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComBlocoDecProcedimento extends PDecProcedimento
{
    private TPontoEntrada _pontoEntrada_;
    private TProcedure _procedure_;
    private TId _id_;
    private TAbreColchete _abreColchete_;
    private PParametros _parametros_;
    private TFechaColchete _fechaColchete_;
    private PBlocoCmd _blocoCmd_;

    public AComBlocoDecProcedimento()
    {
        // Constructor
    }

    public AComBlocoDecProcedimento(
        @SuppressWarnings("hiding") TPontoEntrada _pontoEntrada_,
        @SuppressWarnings("hiding") TProcedure _procedure_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TAbreColchete _abreColchete_,
        @SuppressWarnings("hiding") PParametros _parametros_,
        @SuppressWarnings("hiding") TFechaColchete _fechaColchete_,
        @SuppressWarnings("hiding") PBlocoCmd _blocoCmd_)
    {
        // Constructor
        setPontoEntrada(_pontoEntrada_);

        setProcedure(_procedure_);

        setId(_id_);

        setAbreColchete(_abreColchete_);

        setParametros(_parametros_);

        setFechaColchete(_fechaColchete_);

        setBlocoCmd(_blocoCmd_);

    }

    @Override
    public Object clone()
    {
        return new AComBlocoDecProcedimento(
            cloneNode(this._pontoEntrada_),
            cloneNode(this._procedure_),
            cloneNode(this._id_),
            cloneNode(this._abreColchete_),
            cloneNode(this._parametros_),
            cloneNode(this._fechaColchete_),
            cloneNode(this._blocoCmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComBlocoDecProcedimento(this);
    }

    public TPontoEntrada getPontoEntrada()
    {
        return this._pontoEntrada_;
    }

    public void setPontoEntrada(TPontoEntrada node)
    {
        if(this._pontoEntrada_ != null)
        {
            this._pontoEntrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEntrada_ = node;
    }

    public TProcedure getProcedure()
    {
        return this._procedure_;
    }

    public void setProcedure(TProcedure node)
    {
        if(this._procedure_ != null)
        {
            this._procedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procedure_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TAbreColchete getAbreColchete()
    {
        return this._abreColchete_;
    }

    public void setAbreColchete(TAbreColchete node)
    {
        if(this._abreColchete_ != null)
        {
            this._abreColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreColchete_ = node;
    }

    public PParametros getParametros()
    {
        return this._parametros_;
    }

    public void setParametros(PParametros node)
    {
        if(this._parametros_ != null)
        {
            this._parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametros_ = node;
    }

    public TFechaColchete getFechaColchete()
    {
        return this._fechaColchete_;
    }

    public void setFechaColchete(TFechaColchete node)
    {
        if(this._fechaColchete_ != null)
        {
            this._fechaColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaColchete_ = node;
    }

    public PBlocoCmd getBlocoCmd()
    {
        return this._blocoCmd_;
    }

    public void setBlocoCmd(PBlocoCmd node)
    {
        if(this._blocoCmd_ != null)
        {
            this._blocoCmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoCmd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pontoEntrada_)
            + toString(this._procedure_)
            + toString(this._id_)
            + toString(this._abreColchete_)
            + toString(this._parametros_)
            + toString(this._fechaColchete_)
            + toString(this._blocoCmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pontoEntrada_ == child)
        {
            this._pontoEntrada_ = null;
            return;
        }

        if(this._procedure_ == child)
        {
            this._procedure_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._abreColchete_ == child)
        {
            this._abreColchete_ = null;
            return;
        }

        if(this._parametros_ == child)
        {
            this._parametros_ = null;
            return;
        }

        if(this._fechaColchete_ == child)
        {
            this._fechaColchete_ = null;
            return;
        }

        if(this._blocoCmd_ == child)
        {
            this._blocoCmd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pontoEntrada_ == oldChild)
        {
            setPontoEntrada((TPontoEntrada) newChild);
            return;
        }

        if(this._procedure_ == oldChild)
        {
            setProcedure((TProcedure) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._abreColchete_ == oldChild)
        {
            setAbreColchete((TAbreColchete) newChild);
            return;
        }

        if(this._parametros_ == oldChild)
        {
            setParametros((PParametros) newChild);
            return;
        }

        if(this._fechaColchete_ == oldChild)
        {
            setFechaColchete((TFechaColchete) newChild);
            return;
        }

        if(this._blocoCmd_ == oldChild)
        {
            setBlocoCmd((PBlocoCmd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
