/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADecObj extends PDecObj
{
    private TObject _object_;
    private PTipoClasse _tipoClasse_;
    private TId _id_;
    private TPonto _ponto_;

    public ADecObj()
    {
        // Constructor
    }

    public ADecObj(
        @SuppressWarnings("hiding") TObject _object_,
        @SuppressWarnings("hiding") PTipoClasse _tipoClasse_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setObject(_object_);

        setTipoClasse(_tipoClasse_);

        setId(_id_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ADecObj(
            cloneNode(this._object_),
            cloneNode(this._tipoClasse_),
            cloneNode(this._id_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecObj(this);
    }

    public TObject getObject()
    {
        return this._object_;
    }

    public void setObject(TObject node)
    {
        if(this._object_ != null)
        {
            this._object_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._object_ = node;
    }

    public PTipoClasse getTipoClasse()
    {
        return this._tipoClasse_;
    }

    public void setTipoClasse(PTipoClasse node)
    {
        if(this._tipoClasse_ != null)
        {
            this._tipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoClasse_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._object_)
            + toString(this._tipoClasse_)
            + toString(this._id_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._object_ == child)
        {
            this._object_ = null;
            return;
        }

        if(this._tipoClasse_ == child)
        {
            this._tipoClasse_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._object_ == oldChild)
        {
            setObject((TObject) newChild);
            return;
        }

        if(this._tipoClasse_ == oldChild)
        {
            setTipoClasse((PTipoClasse) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
