/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADivExpMult extends PExpMult
{
    private PExpMult _expMult_;
    private TDiv _div_;
    private PExpUnario _expUnario_;

    public ADivExpMult()
    {
        // Constructor
    }

    public ADivExpMult(
        @SuppressWarnings("hiding") PExpMult _expMult_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PExpUnario _expUnario_)
    {
        // Constructor
        setExpMult(_expMult_);

        setDiv(_div_);

        setExpUnario(_expUnario_);

    }

    @Override
    public Object clone()
    {
        return new ADivExpMult(
            cloneNode(this._expMult_),
            cloneNode(this._div_),
            cloneNode(this._expUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivExpMult(this);
    }

    public PExpMult getExpMult()
    {
        return this._expMult_;
    }

    public void setExpMult(PExpMult node)
    {
        if(this._expMult_ != null)
        {
            this._expMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMult_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PExpUnario getExpUnario()
    {
        return this._expUnario_;
    }

    public void setExpUnario(PExpUnario node)
    {
        if(this._expUnario_ != null)
        {
            this._expUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMult_)
            + toString(this._div_)
            + toString(this._expUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMult_ == child)
        {
            this._expMult_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._expUnario_ == child)
        {
            this._expUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMult_ == oldChild)
        {
            setExpMult((PExpMult) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._expUnario_ == oldChild)
        {
            setExpUnario((PExpUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
