/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AExpExtra extends PExpExtra
{
    private TSepararExpressao _separarExpressao_;
    private PExp _exp_;

    public AExpExtra()
    {
        // Constructor
    }

    public AExpExtra(
        @SuppressWarnings("hiding") TSepararExpressao _separarExpressao_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setSepararExpressao(_separarExpressao_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AExpExtra(
            cloneNode(this._separarExpressao_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpExtra(this);
    }

    public TSepararExpressao getSepararExpressao()
    {
        return this._separarExpressao_;
    }

    public void setSepararExpressao(TSepararExpressao node)
    {
        if(this._separarExpressao_ != null)
        {
            this._separarExpressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separarExpressao_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separarExpressao_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separarExpressao_ == child)
        {
            this._separarExpressao_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separarExpressao_ == oldChild)
        {
            setSepararExpressao((TSepararExpressao) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
