/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AIgualExpIgual extends PExpIgual
{
    private PExpIgual _expIgual_;
    private TIgual _igual_;
    private PExpRelacional _expRelacional_;

    public AIgualExpIgual()
    {
        // Constructor
    }

    public AIgualExpIgual(
        @SuppressWarnings("hiding") PExpIgual _expIgual_,
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_)
    {
        // Constructor
        setExpIgual(_expIgual_);

        setIgual(_igual_);

        setExpRelacional(_expRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AIgualExpIgual(
            cloneNode(this._expIgual_),
            cloneNode(this._igual_),
            cloneNode(this._expRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualExpIgual(this);
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expIgual_)
            + toString(this._igual_)
            + toString(this._expRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
