/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AListaListaExp extends PListaExp
{
    private PExp _exp_;
    private final LinkedList<PExpExtra> _expExtra_ = new LinkedList<PExpExtra>();

    public AListaListaExp()
    {
        // Constructor
    }

    public AListaListaExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _expExtra_)
    {
        // Constructor
        setExp(_exp_);

        setExpExtra(_expExtra_);

    }

    @Override
    public Object clone()
    {
        return new AListaListaExp(
            cloneNode(this._exp_),
            cloneList(this._expExtra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaListaExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PExpExtra> getExpExtra()
    {
        return this._expExtra_;
    }

    public void setExpExtra(List<?> list)
    {
        for(PExpExtra e : this._expExtra_)
        {
            e.parent(null);
        }
        this._expExtra_.clear();

        for(Object obj_e : list)
        {
            PExpExtra e = (PExpExtra) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expExtra_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._expExtra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._expExtra_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PExpExtra> i = this._expExtra_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpExtra) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
