/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AListaParametros extends PParametros
{
    private PParametro _parametro_;
    private final LinkedList<PParametroExtra> _parametroExtra_ = new LinkedList<PParametroExtra>();

    public AListaParametros()
    {
        // Constructor
    }

    public AListaParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _parametroExtra_)
    {
        // Constructor
        setParametro(_parametro_);

        setParametroExtra(_parametroExtra_);

    }

    @Override
    public Object clone()
    {
        return new AListaParametros(
            cloneNode(this._parametro_),
            cloneList(this._parametroExtra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PParametroExtra> getParametroExtra()
    {
        return this._parametroExtra_;
    }

    public void setParametroExtra(List<?> list)
    {
        for(PParametroExtra e : this._parametroExtra_)
        {
            e.parent(null);
        }
        this._parametroExtra_.clear();

        for(Object obj_e : list)
        {
            PParametroExtra e = (PParametroExtra) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametroExtra_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._parametroExtra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._parametroExtra_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PParametroExtra> i = this._parametroExtra_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametroExtra) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
