/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMaisExpSoma extends PExpSoma
{
    private PExpSoma _expSoma_;
    private TMais _mais_;
    private PExpMult _expMult_;

    public AMaisExpSoma()
    {
        // Constructor
    }

    public AMaisExpSoma(
        @SuppressWarnings("hiding") PExpSoma _expSoma_,
        @SuppressWarnings("hiding") TMais _mais_,
        @SuppressWarnings("hiding") PExpMult _expMult_)
    {
        // Constructor
        setExpSoma(_expSoma_);

        setMais(_mais_);

        setExpMult(_expMult_);

    }

    @Override
    public Object clone()
    {
        return new AMaisExpSoma(
            cloneNode(this._expSoma_),
            cloneNode(this._mais_),
            cloneNode(this._expMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaisExpSoma(this);
    }

    public PExpSoma getExpSoma()
    {
        return this._expSoma_;
    }

    public void setExpSoma(PExpSoma node)
    {
        if(this._expSoma_ != null)
        {
            this._expSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSoma_ = node;
    }

    public TMais getMais()
    {
        return this._mais_;
    }

    public void setMais(TMais node)
    {
        if(this._mais_ != null)
        {
            this._mais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mais_ = node;
    }

    public PExpMult getExpMult()
    {
        return this._expMult_;
    }

    public void setExpMult(PExpMult node)
    {
        if(this._expMult_ != null)
        {
            this._expMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSoma_)
            + toString(this._mais_)
            + toString(this._expMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSoma_ == child)
        {
            this._expSoma_ = null;
            return;
        }

        if(this._mais_ == child)
        {
            this._mais_ = null;
            return;
        }

        if(this._expMult_ == child)
        {
            this._expMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSoma_ == oldChild)
        {
            setExpSoma((PExpSoma) newChild);
            return;
        }

        if(this._mais_ == oldChild)
        {
            setMais((TMais) newChild);
            return;
        }

        if(this._expMult_ == oldChild)
        {
            setExpMult((PExpMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
