/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExpRelacional extends PExpRelacional
{
    private PExpRelacional _expRelacional_;
    private TMaiorQue _maiorQue_;
    private PExpSoma _expSoma_;

    public AMaiorExpRelacional()
    {
        // Constructor
    }

    public AMaiorExpRelacional(
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_,
        @SuppressWarnings("hiding") TMaiorQue _maiorQue_,
        @SuppressWarnings("hiding") PExpSoma _expSoma_)
    {
        // Constructor
        setExpRelacional(_expRelacional_);

        setMaiorQue(_maiorQue_);

        setExpSoma(_expSoma_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExpRelacional(
            cloneNode(this._expRelacional_),
            cloneNode(this._maiorQue_),
            cloneNode(this._expSoma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExpRelacional(this);
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    public TMaiorQue getMaiorQue()
    {
        return this._maiorQue_;
    }

    public void setMaiorQue(TMaiorQue node)
    {
        if(this._maiorQue_ != null)
        {
            this._maiorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQue_ = node;
    }

    public PExpSoma getExpSoma()
    {
        return this._expSoma_;
    }

    public void setExpSoma(PExpSoma node)
    {
        if(this._expSoma_ != null)
        {
            this._expSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSoma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelacional_)
            + toString(this._maiorQue_)
            + toString(this._expSoma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        if(this._maiorQue_ == child)
        {
            this._maiorQue_ = null;
            return;
        }

        if(this._expSoma_ == child)
        {
            this._expSoma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        if(this._maiorQue_ == oldChild)
        {
            setMaiorQue((TMaiorQue) newChild);
            return;
        }

        if(this._expSoma_ == oldChild)
        {
            setExpSoma((PExpSoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
