/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMenorExpRelacional extends PExpRelacional
{
    private PExpRelacional _expRelacional_;
    private TMenorQue _menorQue_;
    private PExpSoma _expSoma_;

    public AMenorExpRelacional()
    {
        // Constructor
    }

    public AMenorExpRelacional(
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_,
        @SuppressWarnings("hiding") TMenorQue _menorQue_,
        @SuppressWarnings("hiding") PExpSoma _expSoma_)
    {
        // Constructor
        setExpRelacional(_expRelacional_);

        setMenorQue(_menorQue_);

        setExpSoma(_expSoma_);

    }

    @Override
    public Object clone()
    {
        return new AMenorExpRelacional(
            cloneNode(this._expRelacional_),
            cloneNode(this._menorQue_),
            cloneNode(this._expSoma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExpRelacional(this);
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    public TMenorQue getMenorQue()
    {
        return this._menorQue_;
    }

    public void setMenorQue(TMenorQue node)
    {
        if(this._menorQue_ != null)
        {
            this._menorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorQue_ = node;
    }

    public PExpSoma getExpSoma()
    {
        return this._expSoma_;
    }

    public void setExpSoma(PExpSoma node)
    {
        if(this._expSoma_ != null)
        {
            this._expSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSoma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelacional_)
            + toString(this._menorQue_)
            + toString(this._expSoma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        if(this._menorQue_ == child)
        {
            this._menorQue_ = null;
            return;
        }

        if(this._expSoma_ == child)
        {
            this._expSoma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        if(this._menorQue_ == oldChild)
        {
            setMenorQue((TMenorQue) newChild);
            return;
        }

        if(this._expSoma_ == oldChild)
        {
            setExpSoma((PExpSoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
