/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMetodos extends PMetodos
{
    private final LinkedList<PDecMetodo> _decMetodo_ = new LinkedList<PDecMetodo>();

    public AMetodos()
    {
        // Constructor
    }

    public AMetodos(
        @SuppressWarnings("hiding") List<?> _decMetodo_)
    {
        // Constructor
        setDecMetodo(_decMetodo_);

    }

    @Override
    public Object clone()
    {
        return new AMetodos(
            cloneList(this._decMetodo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetodos(this);
    }

    public LinkedList<PDecMetodo> getDecMetodo()
    {
        return this._decMetodo_;
    }

    public void setDecMetodo(List<?> list)
    {
        for(PDecMetodo e : this._decMetodo_)
        {
            e.parent(null);
        }
        this._decMetodo_.clear();

        for(Object obj_e : list)
        {
            PDecMetodo e = (PDecMetodo) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decMetodo_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decMetodo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decMetodo_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecMetodo> i = this._decMetodo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecMetodo) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
