/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultExpSoma extends PExpSoma
{
    private PExpMult _expMult_;

    public AMultExpSoma()
    {
        // Constructor
    }

    public AMultExpSoma(
        @SuppressWarnings("hiding") PExpMult _expMult_)
    {
        // Constructor
        setExpMult(_expMult_);

    }

    @Override
    public Object clone()
    {
        return new AMultExpSoma(
            cloneNode(this._expMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExpSoma(this);
    }

    public PExpMult getExpMult()
    {
        return this._expMult_;
    }

    public void setExpMult(PExpMult node)
    {
        if(this._expMult_ != null)
        {
            this._expMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMult_ == child)
        {
            this._expMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMult_ == oldChild)
        {
            setExpMult((PExpMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
