/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ANaoCasadoComando extends PComando
{
    private PComandoNaoCasado _comandoNaoCasado_;

    public ANaoCasadoComando()
    {
        // Constructor
    }

    public ANaoCasadoComando(
        @SuppressWarnings("hiding") PComandoNaoCasado _comandoNaoCasado_)
    {
        // Constructor
        setComandoNaoCasado(_comandoNaoCasado_);

    }

    @Override
    public Object clone()
    {
        return new ANaoCasadoComando(
            cloneNode(this._comandoNaoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoCasadoComando(this);
    }

    public PComandoNaoCasado getComandoNaoCasado()
    {
        return this._comandoNaoCasado_;
    }

    public void setComandoNaoCasado(PComandoNaoCasado node)
    {
        if(this._comandoNaoCasado_ != null)
        {
            this._comandoNaoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoNaoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoNaoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoNaoCasado_ == child)
        {
            this._comandoNaoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoNaoCasado_ == oldChild)
        {
            setComandoNaoCasado((PComandoNaoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
