/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ANegExpUnario extends PExpUnario
{
    private TMenos _menos_;
    private PExpUnario _expUnario_;

    public ANegExpUnario()
    {
        // Constructor
    }

    public ANegExpUnario(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpUnario _expUnario_)
    {
        // Constructor
        setMenos(_menos_);

        setExpUnario(_expUnario_);

    }

    @Override
    public Object clone()
    {
        return new ANegExpUnario(
            cloneNode(this._menos_),
            cloneNode(this._expUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegExpUnario(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpUnario getExpUnario()
    {
        return this._expUnario_;
    }

    public void setExpUnario(PExpUnario node)
    {
        if(this._expUnario_ != null)
        {
            this._expUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._expUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expUnario_ == child)
        {
            this._expUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expUnario_ == oldChild)
        {
            setExpUnario((PExpUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
