/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpUnario extends PExpUnario
{
    private TNot _not_;
    private PExpUnario _expUnario_;

    public ANotExpUnario()
    {
        // Constructor
    }

    public ANotExpUnario(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PExpUnario _expUnario_)
    {
        // Constructor
        setNot(_not_);

        setExpUnario(_expUnario_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpUnario(
            cloneNode(this._not_),
            cloneNode(this._expUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpUnario(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PExpUnario getExpUnario()
    {
        return this._expUnario_;
    }

    public void setExpUnario(PExpUnario node)
    {
        if(this._expUnario_ != null)
        {
            this._expUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._expUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._expUnario_ == child)
        {
            this._expUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._expUnario_ == oldChild)
        {
            setExpUnario((PExpUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
