/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AParametroExtra extends PParametroExtra
{
    private TSepararExpressao _separarExpressao_;
    private PParametro _parametro_;

    public AParametroExtra()
    {
        // Constructor
    }

    public AParametroExtra(
        @SuppressWarnings("hiding") TSepararExpressao _separarExpressao_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setSepararExpressao(_separarExpressao_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametroExtra(
            cloneNode(this._separarExpressao_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametroExtra(this);
    }

    public TSepararExpressao getSepararExpressao()
    {
        return this._separarExpressao_;
    }

    public void setSepararExpressao(TSepararExpressao node)
    {
        if(this._separarExpressao_ != null)
        {
            this._separarExpressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separarExpressao_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separarExpressao_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separarExpressao_ == child)
        {
            this._separarExpressao_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separarExpressao_ == oldChild)
        {
            setSepararExpressao((TSepararExpressao) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
