/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private PGenealogia _genealogia_;
    private final LinkedList<PDefClasse> _defClasse_ = new LinkedList<PDefClasse>();

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") PGenealogia _genealogia_,
        @SuppressWarnings("hiding") List<?> _defClasse_)
    {
        // Constructor
        setGenealogia(_genealogia_);

        setDefClasse(_defClasse_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._genealogia_),
            cloneList(this._defClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public PGenealogia getGenealogia()
    {
        return this._genealogia_;
    }

    public void setGenealogia(PGenealogia node)
    {
        if(this._genealogia_ != null)
        {
            this._genealogia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._genealogia_ = node;
    }

    public LinkedList<PDefClasse> getDefClasse()
    {
        return this._defClasse_;
    }

    public void setDefClasse(List<?> list)
    {
        for(PDefClasse e : this._defClasse_)
        {
            e.parent(null);
        }
        this._defClasse_.clear();

        for(Object obj_e : list)
        {
            PDefClasse e = (PDefClasse) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._defClasse_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._genealogia_)
            + toString(this._defClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._genealogia_ == child)
        {
            this._genealogia_ = null;
            return;
        }

        if(this._defClasse_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._genealogia_ == oldChild)
        {
            setGenealogia((PGenealogia) newChild);
            return;
        }

        for(ListIterator<PDefClasse> i = this._defClasse_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDefClasse) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
