/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ARelacao extends PRelacao
{
    private TFamily _family_;
    private PTipoClasse _filha_;
    private TDerives _derives_;
    private TFrom _from_;
    private PTipoClasse _mae_;

    public ARelacao()
    {
        // Constructor
    }

    public ARelacao(
        @SuppressWarnings("hiding") TFamily _family_,
        @SuppressWarnings("hiding") PTipoClasse _filha_,
        @SuppressWarnings("hiding") TDerives _derives_,
        @SuppressWarnings("hiding") TFrom _from_,
        @SuppressWarnings("hiding") PTipoClasse _mae_)
    {
        // Constructor
        setFamily(_family_);

        setFilha(_filha_);

        setDerives(_derives_);

        setFrom(_from_);

        setMae(_mae_);

    }

    @Override
    public Object clone()
    {
        return new ARelacao(
            cloneNode(this._family_),
            cloneNode(this._filha_),
            cloneNode(this._derives_),
            cloneNode(this._from_),
            cloneNode(this._mae_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacao(this);
    }

    public TFamily getFamily()
    {
        return this._family_;
    }

    public void setFamily(TFamily node)
    {
        if(this._family_ != null)
        {
            this._family_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._family_ = node;
    }

    public PTipoClasse getFilha()
    {
        return this._filha_;
    }

    public void setFilha(PTipoClasse node)
    {
        if(this._filha_ != null)
        {
            this._filha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filha_ = node;
    }

    public TDerives getDerives()
    {
        return this._derives_;
    }

    public void setDerives(TDerives node)
    {
        if(this._derives_ != null)
        {
            this._derives_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._derives_ = node;
    }

    public TFrom getFrom()
    {
        return this._from_;
    }

    public void setFrom(TFrom node)
    {
        if(this._from_ != null)
        {
            this._from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._from_ = node;
    }

    public PTipoClasse getMae()
    {
        return this._mae_;
    }

    public void setMae(PTipoClasse node)
    {
        if(this._mae_ != null)
        {
            this._mae_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mae_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._family_)
            + toString(this._filha_)
            + toString(this._derives_)
            + toString(this._from_)
            + toString(this._mae_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._family_ == child)
        {
            this._family_ = null;
            return;
        }

        if(this._filha_ == child)
        {
            this._filha_ = null;
            return;
        }

        if(this._derives_ == child)
        {
            this._derives_ = null;
            return;
        }

        if(this._from_ == child)
        {
            this._from_ = null;
            return;
        }

        if(this._mae_ == child)
        {
            this._mae_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._family_ == oldChild)
        {
            setFamily((TFamily) newChild);
            return;
        }

        if(this._filha_ == oldChild)
        {
            setFilha((PTipoClasse) newChild);
            return;
        }

        if(this._derives_ == oldChild)
        {
            setDerives((TDerives) newChild);
            return;
        }

        if(this._from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(this._mae_ == oldChild)
        {
            setMae((PTipoClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
