/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExpRelacional extends PExpRelacional
{
    private PExpSoma _expSoma_;

    public ASomaExpRelacional()
    {
        // Constructor
    }

    public ASomaExpRelacional(
        @SuppressWarnings("hiding") PExpSoma _expSoma_)
    {
        // Constructor
        setExpSoma(_expSoma_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpRelacional(
            cloneNode(this._expSoma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpRelacional(this);
    }

    public PExpSoma getExpSoma()
    {
        return this._expSoma_;
    }

    public void setExpSoma(PExpSoma node)
    {
        if(this._expSoma_ != null)
        {
            this._expSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSoma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSoma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSoma_ == child)
        {
            this._expSoma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSoma_ == oldChild)
        {
            setExpSoma((PExpSoma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
