/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ATernarioExp extends PExp
{
    private TIf _if_;
    private TParEsq _parEsq_;
    private PExpOr _cond_;
    private TParDir _parDir_;
    private PExp _verdadeiro_;
    private TElse _else_;
    private PExp _falso_;

    public ATernarioExp()
    {
        // Constructor
    }

    public ATernarioExp(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExpOr _cond_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PExp _verdadeiro_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PExp _falso_)
    {
        // Constructor
        setIf(_if_);

        setParEsq(_parEsq_);

        setCond(_cond_);

        setParDir(_parDir_);

        setVerdadeiro(_verdadeiro_);

        setElse(_else_);

        setFalso(_falso_);

    }

    @Override
    public Object clone()
    {
        return new ATernarioExp(
            cloneNode(this._if_),
            cloneNode(this._parEsq_),
            cloneNode(this._cond_),
            cloneNode(this._parDir_),
            cloneNode(this._verdadeiro_),
            cloneNode(this._else_),
            cloneNode(this._falso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernarioExp(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExpOr getCond()
    {
        return this._cond_;
    }

    public void setCond(PExpOr node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PExp getVerdadeiro()
    {
        return this._verdadeiro_;
    }

    public void setVerdadeiro(PExp node)
    {
        if(this._verdadeiro_ != null)
        {
            this._verdadeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._verdadeiro_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PExp getFalso()
    {
        return this._falso_;
    }

    public void setFalso(PExp node)
    {
        if(this._falso_ != null)
        {
            this._falso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._parEsq_)
            + toString(this._cond_)
            + toString(this._parDir_)
            + toString(this._verdadeiro_)
            + toString(this._else_)
            + toString(this._falso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._verdadeiro_ == child)
        {
            this._verdadeiro_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._falso_ == child)
        {
            this._falso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._cond_ == oldChild)
        {
            setCond((PExpOr) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._verdadeiro_ == oldChild)
        {
            setVerdadeiro((PExp) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._falso_ == oldChild)
        {
            setFalso((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
