/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AWhileComandoCasado extends PComandoCasado
{
    private TAs _primeiroAs_;
    private TLong _long_;
    private TAs _segundoAs_;
    private TParEsq _parEsq_;
    private PExp _exp_;
    private TParDir _parDir_;
    private PComandoCasado _comandoCasado_;

    public AWhileComandoCasado()
    {
        // Constructor
    }

    public AWhileComandoCasado(
        @SuppressWarnings("hiding") TAs _primeiroAs_,
        @SuppressWarnings("hiding") TLong _long_,
        @SuppressWarnings("hiding") TAs _segundoAs_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PComandoCasado _comandoCasado_)
    {
        // Constructor
        setPrimeiroAs(_primeiroAs_);

        setLong(_long_);

        setSegundoAs(_segundoAs_);

        setParEsq(_parEsq_);

        setExp(_exp_);

        setParDir(_parDir_);

        setComandoCasado(_comandoCasado_);

    }

    @Override
    public Object clone()
    {
        return new AWhileComandoCasado(
            cloneNode(this._primeiroAs_),
            cloneNode(this._long_),
            cloneNode(this._segundoAs_),
            cloneNode(this._parEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parDir_),
            cloneNode(this._comandoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileComandoCasado(this);
    }

    public TAs getPrimeiroAs()
    {
        return this._primeiroAs_;
    }

    public void setPrimeiroAs(TAs node)
    {
        if(this._primeiroAs_ != null)
        {
            this._primeiroAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primeiroAs_ = node;
    }

    public TLong getLong()
    {
        return this._long_;
    }

    public void setLong(TLong node)
    {
        if(this._long_ != null)
        {
            this._long_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._long_ = node;
    }

    public TAs getSegundoAs()
    {
        return this._segundoAs_;
    }

    public void setSegundoAs(TAs node)
    {
        if(this._segundoAs_ != null)
        {
            this._segundoAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._segundoAs_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PComandoCasado getComandoCasado()
    {
        return this._comandoCasado_;
    }

    public void setComandoCasado(PComandoCasado node)
    {
        if(this._comandoCasado_ != null)
        {
            this._comandoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primeiroAs_)
            + toString(this._long_)
            + toString(this._segundoAs_)
            + toString(this._parEsq_)
            + toString(this._exp_)
            + toString(this._parDir_)
            + toString(this._comandoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primeiroAs_ == child)
        {
            this._primeiroAs_ = null;
            return;
        }

        if(this._long_ == child)
        {
            this._long_ = null;
            return;
        }

        if(this._segundoAs_ == child)
        {
            this._segundoAs_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._comandoCasado_ == child)
        {
            this._comandoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primeiroAs_ == oldChild)
        {
            setPrimeiroAs((TAs) newChild);
            return;
        }

        if(this._long_ == oldChild)
        {
            setLong((TLong) newChild);
            return;
        }

        if(this._segundoAs_ == oldChild)
        {
            setSegundoAs((TAs) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._comandoCasado_ == oldChild)
        {
            setComandoCasado((PComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
