/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        {
            List<PDefClasse> copy = new ArrayList<PDefClasse>(node.getDefClasse());
            Collections.reverse(copy);
            for(PDefClasse e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getGenealogia() != null)
        {
            node.getGenealogia().apply(this);
        }
        outAPrograma(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        {
            List<PRelacaoExtra> copy = new ArrayList<PRelacaoExtra>(node.getRelacaoExtra());
            Collections.reverse(copy);
            for(PRelacaoExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outAGenealogia(node);
    }

    public void inARelacaoExtra(ARelacaoExtra node)
    {
        defaultIn(node);
    }

    public void outARelacaoExtra(ARelacaoExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacaoExtra(ARelacaoExtra node)
    {
        inARelacaoExtra(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        if(node.getEComercial() != null)
        {
            node.getEComercial().apply(this);
        }
        outARelacaoExtra(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getMae() != null)
        {
            node.getMae().apply(this);
        }
        if(node.getFrom() != null)
        {
            node.getFrom().apply(this);
        }
        if(node.getDerives() != null)
        {
            node.getDerives().apply(this);
        }
        if(node.getFilha() != null)
        {
            node.getFilha().apply(this);
        }
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        outARelacao(node);
    }

    public void inADefClasse(ADefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasse(ADefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasse(ADefClasse node)
    {
        inADefClasse(node);
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        if(node.getMetodos() != null)
        {
            node.getMetodos().apply(this);
        }
        if(node.getAtributos() != null)
        {
            node.getAtributos().apply(this);
        }
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        outADefClasse(node);
    }

    public void inAAtributos(AAtributos node)
    {
        defaultIn(node);
    }

    public void outAAtributos(AAtributos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributos(AAtributos node)
    {
        inAAtributos(node);
        {
            List<PDecGeral> copy = new ArrayList<PDecGeral>(node.getDecGeral());
            Collections.reverse(copy);
            for(PDecGeral e : copy)
            {
                e.apply(this);
            }
        }
        outAAtributos(node);
    }

    public void inAObjDecGeral(AObjDecGeral node)
    {
        defaultIn(node);
    }

    public void outAObjDecGeral(AObjDecGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDecGeral(AObjDecGeral node)
    {
        inAObjDecGeral(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjDecGeral(node);
    }

    public void inAVarDecGeral(AVarDecGeral node)
    {
        defaultIn(node);
    }

    public void outAVarDecGeral(AVarDecGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDecGeral(AVarDecGeral node)
    {
        inAVarDecGeral(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarDecGeral(node);
    }

    public void inAConsDecGeral(AConsDecGeral node)
    {
        defaultIn(node);
    }

    public void outAConsDecGeral(AConsDecGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDecGeral(AConsDecGeral node)
    {
        inAConsDecGeral(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsDecGeral(node);
    }

    public void inAMetodos(AMetodos node)
    {
        defaultIn(node);
    }

    public void outAMetodos(AMetodos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetodos(AMetodos node)
    {
        inAMetodos(node);
        {
            List<PDecMetodo> copy = new ArrayList<PDecMetodo>(node.getDecMetodo());
            Collections.reverse(copy);
            for(PDecMetodo e : copy)
            {
                e.apply(this);
            }
        }
        outAMetodos(node);
    }

    public void inAProcedimentoDecMetodo(AProcedimentoDecMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoDecMetodo(AProcedimentoDecMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoDecMetodo(AProcedimentoDecMetodo node)
    {
        inAProcedimentoDecMetodo(node);
        if(node.getDecProcedimento() != null)
        {
            node.getDecProcedimento().apply(this);
        }
        outAProcedimentoDecMetodo(node);
    }

    public void inAFuncaoDecMetodo(AFuncaoDecMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoDecMetodo(AFuncaoDecMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoDecMetodo(AFuncaoDecMetodo node)
    {
        inAFuncaoDecMetodo(node);
        if(node.getDecFuncao() != null)
        {
            node.getDecFuncao().apply(this);
        }
        outAFuncaoDecMetodo(node);
    }

    public void inADecObj(ADecObj node)
    {
        defaultIn(node);
    }

    public void outADecObj(ADecObj node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        inADecObj(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        if(node.getObject() != null)
        {
            node.getObject().apply(this);
        }
        outADecObj(node);
    }

    public void inADecVar(ADecVar node)
    {
        defaultIn(node);
    }

    public void outADecVar(ADecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        inADecVar(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        outADecVar(node);
    }

    public void inADecCons(ADecCons node)
    {
        defaultIn(node);
    }

    public void outADecCons(ADecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        inADecCons(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        outADecCons(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inATipoClasse(ATipoClasse node)
    {
        defaultIn(node);
    }

    public void outATipoClasse(ATipoClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoClasse(ATipoClasse node)
    {
        inATipoClasse(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outATipoClasse(node);
    }

    public void inAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        inAAnswerTipoPrimitivo(node);
        if(node.getAnswer() != null)
        {
            node.getAnswer().apply(this);
        }
        outAAnswerTipoPrimitivo(node);
    }

    public void inANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        inANumberTipoPrimitivo(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberTipoPrimitivo(node);
    }

    public void inAComBlocoDecProcedimento(AComBlocoDecProcedimento node)
    {
        defaultIn(node);
    }

    public void outAComBlocoDecProcedimento(AComBlocoDecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComBlocoDecProcedimento(AComBlocoDecProcedimento node)
    {
        inAComBlocoDecProcedimento(node);
        if(node.getBlocoCmd() != null)
        {
            node.getBlocoCmd().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getPontoEntrada() != null)
        {
            node.getPontoEntrada().apply(this);
        }
        outAComBlocoDecProcedimento(node);
    }

    public void inASemBlocoDecProcedimento(ASemBlocoDecProcedimento node)
    {
        defaultIn(node);
    }

    public void outASemBlocoDecProcedimento(ASemBlocoDecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemBlocoDecProcedimento(ASemBlocoDecProcedimento node)
    {
        inASemBlocoDecProcedimento(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        outASemBlocoDecProcedimento(node);
    }

    public void inAComBlocoDecFuncao(AComBlocoDecFuncao node)
    {
        defaultIn(node);
    }

    public void outAComBlocoDecFuncao(AComBlocoDecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComBlocoDecFuncao(AComBlocoDecFuncao node)
    {
        inAComBlocoDecFuncao(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAComBlocoDecFuncao(node);
    }

    public void inASemBlocoDecFuncao(ASemBlocoDecFuncao node)
    {
        defaultIn(node);
    }

    public void outASemBlocoDecFuncao(ASemBlocoDecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemBlocoDecFuncao(ASemBlocoDecFuncao node)
    {
        inASemBlocoDecFuncao(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outASemBlocoDecFuncao(node);
    }

    public void inAVazioParametros(AVazioParametros node)
    {
        defaultIn(node);
    }

    public void outAVazioParametros(AVazioParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioParametros(AVazioParametros node)
    {
        inAVazioParametros(node);
        outAVazioParametros(node);
    }

    public void inAListaParametros(AListaParametros node)
    {
        defaultIn(node);
    }

    public void outAListaParametros(AListaParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametros(AListaParametros node)
    {
        inAListaParametros(node);
        {
            List<PParametroExtra> copy = new ArrayList<PParametroExtra>(node.getParametroExtra());
            Collections.reverse(copy);
            for(PParametroExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        outAListaParametros(node);
    }

    public void inAParametroExtra(AParametroExtra node)
    {
        defaultIn(node);
    }

    public void outAParametroExtra(AParametroExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroExtra(AParametroExtra node)
    {
        inAParametroExtra(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        if(node.getSepararExpressao() != null)
        {
            node.getSepararExpressao().apply(this);
        }
        outAParametroExtra(node);
    }

    public void inAParametro(AParametro node)
    {
        defaultIn(node);
    }

    public void outAParametro(AParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        inAParametro(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAParametro(node);
    }

    public void inACasadoComando(ACasadoComando node)
    {
        defaultIn(node);
    }

    public void outACasadoComando(ACasadoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACasadoComando(ACasadoComando node)
    {
        inACasadoComando(node);
        if(node.getComandoCasado() != null)
        {
            node.getComandoCasado().apply(this);
        }
        outACasadoComando(node);
    }

    public void inANaoCasadoComando(ANaoCasadoComando node)
    {
        defaultIn(node);
    }

    public void outANaoCasadoComando(ANaoCasadoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoCasadoComando(ANaoCasadoComando node)
    {
        inANaoCasadoComando(node);
        if(node.getComandoNaoCasado() != null)
        {
            node.getComandoNaoCasado().apply(this);
        }
        outANaoCasadoComando(node);
    }

    public void inAIfelseComandoCasado(AIfelseComandoCasado node)
    {
        defaultIn(node);
    }

    public void outAIfelseComandoCasado(AIfelseComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfelseComandoCasado(AIfelseComandoCasado node)
    {
        inAIfelseComandoCasado(node);
        if(node.getCmdElse() != null)
        {
            node.getCmdElse().apply(this);
        }
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getCmdIf() != null)
        {
            node.getCmdIf().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getThat() != null)
        {
            node.getThat().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        outAIfelseComandoCasado(node);
    }

    public void inAWhileComandoCasado(AWhileComandoCasado node)
    {
        defaultIn(node);
    }

    public void outAWhileComandoCasado(AWhileComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileComandoCasado(AWhileComandoCasado node)
    {
        inAWhileComandoCasado(node);
        if(node.getComandoCasado() != null)
        {
            node.getComandoCasado().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getSegundoAs() != null)
        {
            node.getSegundoAs().apply(this);
        }
        if(node.getLong() != null)
        {
            node.getLong().apply(this);
        }
        if(node.getPrimeiroAs() != null)
        {
            node.getPrimeiroAs().apply(this);
        }
        outAWhileComandoCasado(node);
    }

    public void inAAtribuicaoComandoCasado(AAtribuicaoComandoCasado node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoComandoCasado(AAtribuicaoComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoComandoCasado(AAtribuicaoComandoCasado node)
    {
        inAAtribuicaoComandoCasado(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAtribuicaoComandoCasado(node);
    }

    public void inAChamadaComandoCasado(AChamadaComandoCasado node)
    {
        defaultIn(node);
    }

    public void outAChamadaComandoCasado(AChamadaComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaComandoCasado(AChamadaComandoCasado node)
    {
        inAChamadaComandoCasado(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaComandoCasado(node);
    }

    public void inABlocoComandoCasado(ABlocoComandoCasado node)
    {
        defaultIn(node);
    }

    public void outABlocoComandoCasado(ABlocoComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComandoCasado(ABlocoComandoCasado node)
    {
        inABlocoComandoCasado(node);
        if(node.getBlocoCmd() != null)
        {
            node.getBlocoCmd().apply(this);
        }
        outABlocoComandoCasado(node);
    }

    public void inAIfComandoNaoCasado(AIfComandoNaoCasado node)
    {
        defaultIn(node);
    }

    public void outAIfComandoNaoCasado(AIfComandoNaoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfComandoNaoCasado(AIfComandoNaoCasado node)
    {
        inAIfComandoNaoCasado(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getThat() != null)
        {
            node.getThat().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        outAIfComandoNaoCasado(node);
    }

    public void inAIfelseComandoNaoCasado(AIfelseComandoNaoCasado node)
    {
        defaultIn(node);
    }

    public void outAIfelseComandoNaoCasado(AIfelseComandoNaoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfelseComandoNaoCasado(AIfelseComandoNaoCasado node)
    {
        inAIfelseComandoNaoCasado(node);
        if(node.getCmdElse() != null)
        {
            node.getCmdElse().apply(this);
        }
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getCmdIf() != null)
        {
            node.getCmdIf().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getThat() != null)
        {
            node.getThat().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        outAIfelseComandoNaoCasado(node);
    }

    public void inAWhileComandoNaoCasado(AWhileComandoNaoCasado node)
    {
        defaultIn(node);
    }

    public void outAWhileComandoNaoCasado(AWhileComandoNaoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileComandoNaoCasado(AWhileComandoNaoCasado node)
    {
        inAWhileComandoNaoCasado(node);
        if(node.getComandoNaoCasado() != null)
        {
            node.getComandoNaoCasado().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getSegundoAs() != null)
        {
            node.getSegundoAs().apply(this);
        }
        if(node.getLong() != null)
        {
            node.getLong().apply(this);
        }
        if(node.getPrimeiroAs() != null)
        {
            node.getPrimeiroAs().apply(this);
        }
        outAWhileComandoNaoCasado(node);
    }

    public void inABlocoCmd(ABlocoCmd node)
    {
        defaultIn(node);
    }

    public void outABlocoCmd(ABlocoCmd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoCmd(ABlocoCmd node)
    {
        inABlocoCmd(node);
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDecGeral> copy = new ArrayList<PDecGeral>(node.getDecGeral());
            Collections.reverse(copy);
            for(PDecGeral e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        outABlocoCmd(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getFalso() != null)
        {
            node.getFalso().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getVerdadeiro() != null)
        {
            node.getVerdadeiro().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outATernarioExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getExpOr() != null)
        {
            node.getExpOr().apply(this);
        }
        outAOrExp(node);
    }

    public void inAOrExpOr(AOrExpOr node)
    {
        defaultIn(node);
    }

    public void outAOrExpOr(AOrExpOr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExpOr(AOrExpOr node)
    {
        inAOrExpOr(node);
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpOr() != null)
        {
            node.getExpOr().apply(this);
        }
        outAOrExpOr(node);
    }

    public void inAAndExpOr(AAndExpOr node)
    {
        defaultIn(node);
    }

    public void outAAndExpOr(AAndExpOr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExpOr(AAndExpOr node)
    {
        inAAndExpOr(node);
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        outAAndExpOr(node);
    }

    public void inAAndExpAnd(AAndExpAnd node)
    {
        defaultIn(node);
    }

    public void outAAndExpAnd(AAndExpAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExpAnd(AAndExpAnd node)
    {
        inAAndExpAnd(node);
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getExpAnd() != null)
        {
            node.getExpAnd().apply(this);
        }
        outAAndExpAnd(node);
    }

    public void inAIgualExpAnd(AIgualExpAnd node)
    {
        defaultIn(node);
    }

    public void outAIgualExpAnd(AIgualExpAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpAnd(AIgualExpAnd node)
    {
        inAIgualExpAnd(node);
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        outAIgualExpAnd(node);
    }

    public void inAIgualExpIgual(AIgualExpIgual node)
    {
        defaultIn(node);
    }

    public void outAIgualExpIgual(AIgualExpIgual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpIgual(AIgualExpIgual node)
    {
        inAIgualExpIgual(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getExpIgual() != null)
        {
            node.getExpIgual().apply(this);
        }
        outAIgualExpIgual(node);
    }

    public void inARelacionalExpIgual(ARelacionalExpIgual node)
    {
        defaultIn(node);
    }

    public void outARelacionalExpIgual(ARelacionalExpIgual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacionalExpIgual(ARelacionalExpIgual node)
    {
        inARelacionalExpIgual(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outARelacionalExpIgual(node);
    }

    public void inAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        inAMaiorExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        if(node.getMaiorQue() != null)
        {
            node.getMaiorQue().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMaiorExpRelacional(node);
    }

    public void inAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        inAMenorExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        if(node.getMenorQue() != null)
        {
            node.getMenorQue().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMenorExpRelacional(node);
    }

    public void inASomaExpRelacional(ASomaExpRelacional node)
    {
        defaultIn(node);
    }

    public void outASomaExpRelacional(ASomaExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpRelacional(ASomaExpRelacional node)
    {
        inASomaExpRelacional(node);
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outASomaExpRelacional(node);
    }

    public void inAMaisExpSoma(AMaisExpSoma node)
    {
        defaultIn(node);
    }

    public void outAMaisExpSoma(AMaisExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisExpSoma(AMaisExpSoma node)
    {
        inAMaisExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        if(node.getMais() != null)
        {
            node.getMais().apply(this);
        }
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outAMaisExpSoma(node);
    }

    public void inAMenosExpSoma(AMenosExpSoma node)
    {
        defaultIn(node);
    }

    public void outAMenosExpSoma(AMenosExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExpSoma(AMenosExpSoma node)
    {
        inAMenosExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getExpSoma() != null)
        {
            node.getExpSoma().apply(this);
        }
        outAMenosExpSoma(node);
    }

    public void inAMultExpSoma(AMultExpSoma node)
    {
        defaultIn(node);
    }

    public void outAMultExpSoma(AMultExpSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExpSoma(AMultExpSoma node)
    {
        inAMultExpSoma(node);
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outAMultExpSoma(node);
    }

    public void inAMultExpMult(AMultExpMult node)
    {
        defaultIn(node);
    }

    public void outAMultExpMult(AMultExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExpMult(AMultExpMult node)
    {
        inAMultExpMult(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outAMultExpMult(node);
    }

    public void inADivExpMult(ADivExpMult node)
    {
        defaultIn(node);
    }

    public void outADivExpMult(ADivExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExpMult(ADivExpMult node)
    {
        inADivExpMult(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getExpMult() != null)
        {
            node.getExpMult().apply(this);
        }
        outADivExpMult(node);
    }

    public void inAUnarioExpMult(AUnarioExpMult node)
    {
        defaultIn(node);
    }

    public void outAUnarioExpMult(AUnarioExpMult node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnarioExpMult(AUnarioExpMult node)
    {
        inAUnarioExpMult(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        outAUnarioExpMult(node);
    }

    public void inANotExpUnario(ANotExpUnario node)
    {
        defaultIn(node);
    }

    public void outANotExpUnario(ANotExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotExpUnario(ANotExpUnario node)
    {
        inANotExpUnario(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        outANotExpUnario(node);
    }

    public void inANegExpUnario(ANegExpUnario node)
    {
        defaultIn(node);
    }

    public void outANegExpUnario(ANegExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegExpUnario(ANegExpUnario node)
    {
        inANegExpUnario(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        outANegExpUnario(node);
    }

    public void inAFatorExpUnario(AFatorExpUnario node)
    {
        defaultIn(node);
    }

    public void outAFatorExpUnario(AFatorExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorExpUnario(AFatorExpUnario node)
    {
        inAFatorExpUnario(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAFatorExpUnario(node);
    }

    public void inARealFator(ARealFator node)
    {
        defaultIn(node);
    }

    public void outARealFator(ARealFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealFator(ARealFator node)
    {
        inARealFator(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outARealFator(node);
    }

    public void inAInteiroFator(AInteiroFator node)
    {
        defaultIn(node);
    }

    public void outAInteiroFator(AInteiroFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroFator(AInteiroFator node)
    {
        inAInteiroFator(node);
        if(node.getInteiro() != null)
        {
            node.getInteiro().apply(this);
        }
        outAInteiroFator(node);
    }

    public void inASimFator(ASimFator node)
    {
        defaultIn(node);
    }

    public void outASimFator(ASimFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimFator(ASimFator node)
    {
        inASimFator(node);
        if(node.getSim() != null)
        {
            node.getSim().apply(this);
        }
        outASimFator(node);
    }

    public void inANaoFator(ANaoFator node)
    {
        defaultIn(node);
    }

    public void outANaoFator(ANaoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoFator(ANaoFator node)
    {
        inANaoFator(node);
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        outANaoFator(node);
    }

    public void inAIdFator(AIdFator node)
    {
        defaultIn(node);
    }

    public void outAIdFator(AIdFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdFator(AIdFator node)
    {
        inAIdFator(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdFator(node);
    }

    public void inAAcessoAtributoFator(AAcessoAtributoFator node)
    {
        defaultIn(node);
    }

    public void outAAcessoAtributoFator(AAcessoAtributoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoAtributoFator(AAcessoAtributoFator node)
    {
        inAAcessoAtributoFator(node);
        if(node.getAcessoAtributo() != null)
        {
            node.getAcessoAtributo().apply(this);
        }
        outAAcessoAtributoFator(node);
    }

    public void inAChamadaFator(AChamadaFator node)
    {
        defaultIn(node);
    }

    public void outAChamadaFator(AChamadaFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaFator(AChamadaFator node)
    {
        inAChamadaFator(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaFator(node);
    }

    public void inAParensFator(AParensFator node)
    {
        defaultIn(node);
    }

    public void outAParensFator(AParensFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParensFator(AParensFator node)
    {
        inAParensFator(node);
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        outAParensFator(node);
    }

    public void inABlocoFator(ABlocoFator node)
    {
        defaultIn(node);
    }

    public void outABlocoFator(ABlocoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoFator(ABlocoFator node)
    {
        inABlocoFator(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outABlocoFator(node);
    }

    public void inAAcessoAcessoAtributo(AAcessoAcessoAtributo node)
    {
        defaultIn(node);
    }

    public void outAAcessoAcessoAtributo(AAcessoAcessoAtributo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoAcessoAtributo(AAcessoAcessoAtributo node)
    {
        inAAcessoAcessoAtributo(node);
        if(node.getAtributo() != null)
        {
            node.getAtributo().apply(this);
        }
        {
            List<TIdComposto> copy = new ArrayList<TIdComposto>(node.getIdComposto());
            Collections.reverse(copy);
            for(TIdComposto e : copy)
            {
                e.apply(this);
            }
        }
        outAAcessoAcessoAtributo(node);
    }

    public void inABlocoBlocoExp(ABlocoBlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoBlocoExp(ABlocoBlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoBlocoExp(ABlocoBlocoExp node)
    {
        inABlocoBlocoExp(node);
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PDecGeral> copy = new ArrayList<PDecGeral>(node.getDecGeral());
            Collections.reverse(copy);
            for(PDecGeral e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        outABlocoBlocoExp(node);
    }

    public void inAAtributoAtributo(AAtributoAtributo node)
    {
        defaultIn(node);
    }

    public void outAAtributoAtributo(AAtributoAtributo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributoAtributo(AAtributoAtributo node)
    {
        inAAtributoAtributo(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAtributoAtributo(node);
    }

    public void inAChamadaChamada(AChamadaChamada node)
    {
        defaultIn(node);
    }

    public void outAChamadaChamada(AChamadaChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaChamada(AChamadaChamada node)
    {
        inAChamadaChamada(node);
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        {
            List<TIdComposto> copy = new ArrayList<TIdComposto>(node.getIdComposto());
            Collections.reverse(copy);
            for(TIdComposto e : copy)
            {
                e.apply(this);
            }
        }
        outAChamadaChamada(node);
    }

    public void inAVaziaListaExp(AVaziaListaExp node)
    {
        defaultIn(node);
    }

    public void outAVaziaListaExp(AVaziaListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVaziaListaExp(AVaziaListaExp node)
    {
        inAVaziaListaExp(node);
        outAVaziaListaExp(node);
    }

    public void inAListaListaExp(AListaListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaListaExp(AListaListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaListaExp(AListaListaExp node)
    {
        inAListaListaExp(node);
        {
            List<PExpExtra> copy = new ArrayList<PExpExtra>(node.getExpExtra());
            Collections.reverse(copy);
            for(PExpExtra e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAListaListaExp(node);
    }

    public void inAExpExtra(AExpExtra node)
    {
        defaultIn(node);
    }

    public void outAExpExtra(AExpExtra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpExtra(AExpExtra node)
    {
        inAExpExtra(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getSepararExpressao() != null)
        {
            node.getSepararExpressao().apply(this);
        }
        outAExpExtra(node);
    }
}
