/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPIgnore().apply(this);
        outStart(node);
    }

    public void inAEmptyIgnore(AEmptyIgnore node)
    {
        defaultIn(node);
    }

    public void outAEmptyIgnore(AEmptyIgnore node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyIgnore(AEmptyIgnore node)
    {
        inAEmptyIgnore(node);
        outAEmptyIgnore(node);
    }
}
