/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TAslongas extends Token
{
    public TAslongas()
    {
        super.setText("as long as");
    }

    public TAslongas(int line, int pos)
    {
        super.setText("as long as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAslongas(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAslongas(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAslongas text.");
    }
}
